spring:
  # Deaktivieren der Datenbank für lokale Entwicklung
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: deka-client
            client-secret: your-client-secret
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/deka
            authorization-uri: http://localhost:8081/realms/deka/protocol/openid-connect/auth
            token-uri: http://localhost:8081/realms/deka/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8081/realms/deka/protocol/openid-connect/certs
            user-info-uri: http://localhost:8081/realms/deka/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

app:
  cors:
    allowed-origins: http://localhost:4200
  auth:
    cookie:
      name: auth_sid
      domain: localhost
      secure: false # in local dev environment
      max-age: 3600 # 1 hour
    session:
      storage: in-memory
